services:
  stalker-bot:
    container_name: stalker-bot
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - lavalink
    env_file:
      - .env
    restart: always
    networks:
      - stalker-bot

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "127.0.0.1:${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: "${MONGO_DATABASE_NAME}:${MONGO_PORT}"
    networks:
      - stalker-bot

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:latest
    container_name: lavalink
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins/:/opt/Lavalink/plugins/
    ports:
      - "127.0.0.1:${LAVALINK_PORT}:${LAVALINK_PORT}"
    networks:
      - stalker-bot

  yt-cipher:
    image: ghcr.io/kikkia/yt-cipher:master
    container_name: yt-cipher
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:8001:8001"
    environment:
      - API_TOKEN=${YT_CIPHER_API_TOKEN}
    networks:
      - stalker-bot

volumes:
  mongo_data:
  lavalink_plugins:

networks:
  stalker-bot:
    name: stalker-bot
